language: python
python:
    - "3.4"
cache:
    - pip3
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install eukleides libxml2-utils gettext texlive-latex-base texlive-luatex texlive-latex-recommended texlive-xetex texlive-pstricks texlive-font-utils texlive-latex-extra texlive-base texlive-science texlive-pictures texlive-generic-recommended texlive-fonts-recommended texlive-fonts-extra
install:
    - "pip3 install --force -r requirements.txt --use-mirrors"
    - "pip3 install coverage"
    - "pip3 install coveralls"
script:
    - "coverage run --source=mathmaker setup.py test"
after_success:
    coveralls