# SOFTWARE'S CONFIGURATION FILE

PATHS:
    EUKTOEPS: euktoeps
    EUKTOEPS_OPTIONS: -i \usepackage{eukleides,graphicx,textcomp}
    XMLLINT: xmllint

LOCALES:
    # Available values can be checked in the locale directory.
    # So far (2012/05/01), available values are en, fr and fr_FR.
    LANGUAGE: fr_FR
    ENCODING: UTF-8
    # Values can be 'euro', 'sterling', 'dollar'
    CURRENCY: euro

LATEX:
    FONT:

